package hospital;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/*A class HospitalService is given to you. Implement the following features in the class.
Methods : public 
addHospital(): This method should receive hospital details 
 as arguments and add to ArrayList of type Hospital and return the generated hospital 
code.
Note : Hospital Code is not given as argument but it should be 
 autogenerated while creating object. It should start from 100.
 getHospitals() : This method should return existing hospitals 
names and its codes in the form of Map variable that contains Hospital 
Code as key (Integer) and Hospital name as Value (String).
 getHospitalDetails() : This method should receive hospital code 
as argument and return the matching object of hospital after searching in 
the ArrayList. Return null if object not found.*/


public class HospitalService {
    private List<Hospital> hospitals = new ArrayList<>();
    private int hospitalCodeCounter = 100;

    // Method to add a hospital and generate hospital code
    public int addHospital(String hospitalName, List<String> listOfTreatments, String contactPerson, String contactNumber, String location) {
        Hospital hospital = new Hospital(hospitalName, listOfTreatments, contactPerson, contactNumber, location);
        hospital.setHospitalCode(hospitalCodeCounter++);
        hospitals.add(hospital);
        return hospital.getHospitalCode();
    }

    // Method to get a Map of hospital codes and hospital names
    public Map<Integer, String> getHospitals() {
        Map<Integer, String> hospitalMap = new HashMap<>();
        for (Hospital hospital : hospitals) {
            hospitalMap.put(hospital.getHospitalCode(), hospital.getHospitalName());
        }
        return hospitalMap;
    }

    // Method to get hospital details by hospital code
    public Hospital getHospitalDetails(int hospitalCode) {
        for (Hospital hospital : hospitals) {
            if (hospital.getHospitalCode() == hospitalCode) {
                return hospital;
            }
        }
        return null;
    }
}

